name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Deploy to Tanzu Platform on Commit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nemearegistry01.azurecr.io
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      - name: Deploy application to Tanzu Platform
        uses: viktoriousss/tanzu-deploy-action@v0.9
        with:
          tanzu_api_token: ${{ secrets.TanzuApiToken }}
          container_registry: nemearegistry01.azurecr.io/tanzubuild/{name}
          # buildPlanSource: custom-build-plan
          project: EMEA
          space: viktorious-space01
